"""The public Organization bootstrap API -- ``POST /api/v1/
organizations``. Phase 3 backend preparation (PROJECT_STATE.md), not a
Phase 2 milestone and not part of the Auth/Identity work's own scope: it
exists to close the one real gap that work left behind -- a newly
registered, logged-in user has no ``organization_id`` to call any
Scanning route with at all (``RegisterUserUseCase`` deliberately creates
only a ``User`` row; see its own docstring).

One route, deliberately: create an organization and become its Owner in
the same call. No list/get/rename/member-management routes -- those
remain future work (member listing has no HTTP surface yet either; see
``OrganizationRepositoryPort.list_members``). This is the minimum
mechanism for ``register -> login -> create an organization (obtaining
membership) -> create/run/poll scans`` end-to-end, nothing more.

Requires ``get_current_user`` (a valid ``access_token`` cookie) but not
``require_organization_member`` -- there is, by definition, no
organization to already be a member of yet.

``organization_id`` is generated by the ``get_new_organization_id``
dependency (app/api/dependencies.py) *before* this handler runs, not
inside ``CreateOrganizationUseCase`` like every other identity use case
generates its own id -- see that dependency's own docstring for why
``organizations``' self-referential RLS policy forces the id to exist
before the RLS-scoped session housing the INSERT can even open.
"""

from __future__ import annotations

from uuid import UUID

from fastapi import APIRouter, Depends, Response, status

from app.api.dependencies import (
    get_create_organization_use_case,
    get_current_user,
    get_new_organization_id,
)
from app.api.v1.organization_schemas import OrganizationCreateRequest, OrganizationResponse
from app.application.identity.create_organization import CreateOrganizationUseCase
from app.domain.identity.entities import User

router = APIRouter(prefix="/organizations", tags=["organizations"])


@router.post("", status_code=status.HTTP_201_CREATED)
async def create_organization(
    payload: OrganizationCreateRequest,
    response: Response,
    organization_id: UUID = Depends(get_new_organization_id),
    create_organization_use_case: CreateOrganizationUseCase = Depends(
        get_create_organization_use_case
    ),
    current_user: User = Depends(get_current_user),
) -> OrganizationResponse:
    """Creates an ``Organization`` plus one ``OrganizationMember`` row
    for ``current_user`` with role ``OWNER``/status ``ACTIVE`` --
    everything a subsequent Scanning-route call needs
    (``require_organization_member``) to succeed for this same caller.

    Raises (via the global exception handler, app/main.py) HTTP 409 if
    ``payload.slug`` is already taken. Requires a valid ``access_token``
    cookie (401 otherwise, see ``get_current_user``); does not require
    existing organization membership, since none can exist yet.
    """
    organization = await create_organization_use_case.execute(
        organization_id=organization_id,
        name=payload.name,
        slug=payload.slug,
        owner_user_id=current_user.id,
    )
    response.headers["Location"] = f"/api/v1/organizations/{organization.id}"
    return OrganizationResponse(
        id=organization.id, name=organization.name, slug=organization.slug
    )
