"""Alembic migration environment, async-engine flavored.

Deliberately reads ``DATABASE_URL`` straight from the environment rather
than going through ``app.config.get_settings()``. ``Settings`` (Milestone
1, locked) validates a full ``WorkerRole``-shaped process -- it demands
``REDIS_URL``, MinIO credentials, and (for the API role) ``JWT_SECRET``
before it will construct at all, because those are real requirements for
the three processes that role enum models (api, ingestion_worker,
scanner_worker). Alembic is not one of those processes; it is a
standalone CLI tool with exactly one dependency, the database. Reusing
``Settings`` here would force every migration run to also supply queue
and object-storage credentials it never touches, and adding a fourth
``WorkerRole`` member just to satisfy that validator would be schema
creep in the wrong file for a problem this module can solve on its own
by reading one environment variable directly.

Uses the async engine + ``run_sync`` recipe (not a second, sync-driver
connection string) so ``DATABASE_URL`` -- ``postgresql+asyncpg://...`` --
stays the single connection string this codebase ever configures.
"""

from __future__ import annotations

import asyncio
import os
from logging.config import fileConfig

from sqlalchemy import Connection, pool
from sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine

# Importing this package populates Base.metadata with every mapped table
# (see app/infrastructure/db/models/__init__.py) -- required for
# `alembic revision --autogenerate` to see the schema, even though this
# project's own migrations are hand-written, not autogenerated.
import app.infrastructure.db.models  # noqa: F401
from alembic import context
from app.infrastructure.db.base import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _database_url() -> str:
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError(
            "DATABASE_URL is not set. Alembic needs it directly (not via "
            "app.config.Settings -- see this module's docstring)."
        )
    return url


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a live database connection --
    ``alembic upgrade --sql``."""
    context.configure(
        url=_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def _do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()


async def _run_migrations_online_async() -> None:
    connectable: AsyncEngine = create_async_engine(_database_url(), poolclass=pool.NullPool)
    async with connectable.connect() as connection:
        await connection.run_sync(_do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(_run_migrations_online_async())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
