"""initial schema

Revision ID: 6bdbf0ab25b0
Revises:
Create Date: 2026-07-24 19:27:29.786098

Table DDL below is Alembic-autogenerated from
``app.infrastructure.db.models`` and matches those models exactly. The
Row-Level Security section at the end of ``upgrade()`` (and the mirrored
teardown at the start of ``downgrade()``) is hand-written -- autogenerate
has no concept of RLS policies, and PROJECT_STATE.md section 3 requires
tenant isolation to exist "from day one," not as a follow-up migration.

DESIGN NOTE -- discovered during this milestone's implementation and
recorded here per the workflow rule requiring a genuine gap to be
explained before adopting its fix, not silently diverged from:

PROJECT_STATE.md section 3's original decision combined tenant isolation
and soft-delete visibility into one RLS predicate: ``USING (org_id =
current_setting('app.current_org_id') AND deleted_at IS NULL)``. That
predicate is unimplementable as a single ``FOR ALL`` policy. PostgreSQL
checks a table's ``SELECT``-relevant ``USING`` clause against the
resulting row of an ``UPDATE`` in addition to whatever ``WITH CHECK`` is
given -- an ``UPDATE`` implicitly requires ``SELECT`` rights on the row
it produces, and Postgres enforces that with the same clause that
filters plain reads. This is real, confirmed, currently-still-current
Postgres behavior (see the pgsql-hackers thread "Bug: RLS policy FOR
SELECT is used to check new rows," Oct 2023, where a core developer
agrees the behavior is arguably wrong but describes it as long-standing
and not changed). Concretely: with ``deleted_at IS NULL`` in the policy,
the very ``UPDATE`` that sets ``deleted_at`` produces a row that fails
its own table's read policy, so Postgres rejects it with "new row
violates row-level security policy" -- verified against a real Postgres
16 instance, not assumed from documentation alone, including confirming
that a permissive ``WITH CHECK (true)`` does not help, since the
``SELECT`` policy is what is actually rejecting the new row, not the
``WITH CHECK``.

There is no policy structure (separate per-command policies included)
that keeps ``deleted_at`` filtering inside RLS while still allowing an
ordinary ``UPDATE`` to set it -- the ``SELECT``-side check on the new row
is unconditional. The fix adopted here: RLS enforces the part of the
original predicate that is actually about tenant isolation --
``organization_id`` (or, for ``organizations`` itself, ``id``) -- and
nothing else. ``deleted_at`` filtering moves to an explicit ``WHERE
deleted_at IS NULL`` in the repository read methods for the five
soft-delete tables (app/infrastructure/db/repositories/), the same way
every other query-level filter in this codebase is expressed. This does
not weaken tenant isolation -- the property RLS exists to guarantee is
unchanged and still enforced by the database itself, not by application
code remembering a WHERE clause. It only relocates a display concern
(hide deleted rows from normal reads) that never depended on RLS in the
first place: ``users`` is soft-deleted with no RLS policy at all
(app/infrastructure/db/models/identity.py), and that filtering has
always been the repository's job.

Policy predicate per table:
  - ``organizations`` keys off its own ``id``, not an ``organization_id``
    column it doesn't have -- this table *is* the tenant boundary.
  - Every other org-scoped table (append-only tables, the four other
    soft-delete tables, ``organization_members``, and ``scan_scopes``)
    uses a plain ``organization_id = current_setting(...)`` predicate --
    identical for ``USING`` and ``WITH CHECK``.
  - ``feature_flags`` is the one exception with a deliberately different
    ``WITH CHECK``: its ``USING`` allows rows where ``organization_id IS
    NULL`` (the global-default row for a key) to be read under every
    tenant context, but its ``WITH CHECK`` requires an exact org match --
    a tenant session may read a global default but never write one. This
    asymmetry does not hit the same UPDATE-vs-new-row problem described
    above because no ordinary write to a tenant's own flag row changes
    its ``organization_id``.

Tables with no ``organization_id`` at all -- ``users``, ``oauth_accounts``,
``refresh_tokens``, ``system_settings`` -- get no RLS policy: they are not
tenant data (see each model's docstring in app/infrastructure/db/models/).

``FORCE ROW LEVEL SECURITY`` is applied everywhere a policy is created so
that even the table-owning role (the only DB role this milestone defines)
is subject to it -- belt-and-suspenders with the network segmentation
planned for Phase 9, not a substitute for it.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bdbf0ab25b0"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

# Every org-scoped table except `organizations` itself (keyed off `id`,
# not `organization_id` -- see module docstring) and `feature_flags`
# (needs a genuinely different WITH CHECK -- see its call site below).
# All of these share the same predicate: `organization_id = :org`, with
# no `deleted_at` clause -- see the DESIGN NOTE above for why soft-delete
# visibility is a repository-level concern instead.
_ORG_SCOPED_TABLES = (
    "assets",
    "findings",
    "scans",
    "reports",
    "organization_members",
    "audit_logs",
    "asset_observations",
    "asset_relationships",
    "scan_scopes",
    "scan_workflow_steps",
    "finding_occurrences",
    "finding_analyses",
    "finding_status_history",
)

_ORG_ID_GUC = "current_setting('app.current_org_id')::uuid"


def _enable_rls(table: str, using: str, check: str | None = None) -> None:
    """``check`` defaults to ``using`` when omitted. ``feature_flags`` is
    the one table that still needs a genuinely different ``check`` (see
    its call site below) -- every other table's ``USING`` and
    ``WITH CHECK`` are identical now; see the DESIGN NOTE above for why
    ``deleted_at`` was removed from this policy entirely rather than
    kept in an asymmetric USING/WITH CHECK split.
    """
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON {table} "
        f"USING ({using}) WITH CHECK ({check if check is not None else using})"
    )


def _disable_rls(table: str) -> None:
    op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "system_settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("hashed_password", sa.Text(), nullable=True),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "assets",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "asset_type",
            sa.Enum(
                "DOMAIN",
                "SUBDOMAIN",
                "IP",
                "PORT",
                "TECHNOLOGY",
                "CERTIFICATE",
                "ENDPOINT",
                name="assettype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "INACTIVE", "ARCHIVED", name="assetstatus", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("asset_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("parent_asset_id", sa.Uuid(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "asset_type", "value"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("resource_type", sa.Text(), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("audit_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feature_flags",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", "organization_id", name="uq_feature_flags_key_org"),
    )
    op.create_index(
        "uq_feature_flags_key_global",
        "feature_flags",
        ["key"],
        unique=True,
        postgresql_where="organization_id IS NULL",
    )
    op.create_table(
        "oauth_accounts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_account_id", sa.Text(), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_account_id"),
    )
    op.create_table(
        "organization_members",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "OWNER",
                "ADMIN",
                "MEMBER",
                "VIEWER",
                name="organizationrole",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INVITED",
                "REMOVED",
                name="membershipstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "user_id"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "scan_scopes",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("target_value", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scans",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("target", sa.Text(), nullable=False),
        sa.Column("scanner_name", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="scanstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("triggered_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["triggered_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "asset_observations",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("observation_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "asset_relationships",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("source_asset_id", sa.Uuid(), nullable=False),
        sa.Column("target_asset_id", sa.Uuid(), nullable=False),
        sa.Column("relationship_type", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "source_asset_id", "target_asset_id", "relationship_type"
        ),
    )
    op.create_table(
        "findings",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "TRIAGED",
                "CONFIRMED",
                "FALSE_POSITIVE",
                "FIXED",
                "ACCEPTED_RISK",
                "WONT_FIX",
                name="findingstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "confidence",
            sa.Enum(
                "UNCONFIRMED",
                "CONFIRMED",
                "FALSE_POSITIVE",
                name="confidencelevel",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "ai_severity_level",
            sa.Enum(
                "INFO",
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="severitylevel",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column("cvss_score", sa.Float(), nullable=True),
        sa.Column("cvss_vector", sa.Text(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "fingerprint"),
    )
    op.create_table(
        "reports",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=True),
        sa.Column(
            "format",
            sa.Enum("HTML", "PDF", "DOCX", name="reportformat", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("storage_key", sa.Text(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scan_workflow_steps",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column(
            "step_name",
            sa.Enum(
                "VALIDATE_TARGET",
                "EXECUTE_SCANNER",
                "NORMALIZE",
                "DEDUPLICATE",
                "CORRELATE",
                "ENRICH",
                "AI_ANALYZE",
                "PERSIST",
                name="workflowstepname",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "SKIPPED",
                name="workflowstepstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scan_id", "step_order"),
    )
    op.create_table(
        "finding_analyses",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        sa.Column("kb_version", sa.Text(), nullable=True),
        sa.Column("model_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ai_summary", sa.Text(), nullable=True),
        sa.Column(
            "ai_severity_estimate",
            sa.Enum(
                "INFO",
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="severitylevel",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column("remediation_advice", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "finding_occurrences",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("raw_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "finding_status_history",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "NEW",
                "TRIAGED",
                "CONFIRMED",
                "FALSE_POSITIVE",
                "FIXED",
                "ACCEPTED_RISK",
                "WONT_FIX",
                name="findingstatus",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "NEW",
                "TRIAGED",
                "CONFIRMED",
                "FALSE_POSITIVE",
                "FIXED",
                "ACCEPTED_RISK",
                "WONT_FIX",
                name="findingstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["changed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # --- Row-Level Security (PROJECT_STATE.md section 3, as amended by
    # the DESIGN NOTE above) ---
    # organizations keys off its own id, not organization_id.
    _enable_rls("organizations", f"id = {_ORG_ID_GUC}")
    for table in _ORG_SCOPED_TABLES:
        _enable_rls(table, f"organization_id = {_ORG_ID_GUC}")
    # feature_flags: a global row (organization_id IS NULL) is visible
    # under every tenant context for reads, but a tenant session may only
    # ever write a row for its own org -- see the DESIGN NOTE above.
    _enable_rls(
        "feature_flags",
        f"organization_id = {_ORG_ID_GUC} OR organization_id IS NULL",
        check=f"organization_id = {_ORG_ID_GUC}",
    )


def downgrade() -> None:
    # --- Row-Level Security teardown (mirrors upgrade()) ---
    _disable_rls("organizations")
    for table in _ORG_SCOPED_TABLES:
        _disable_rls(table)
    _disable_rls("feature_flags")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("finding_status_history")
    op.drop_table("finding_occurrences")
    op.drop_table("finding_analyses")
    op.drop_table("scan_workflow_steps")
    op.drop_table("reports")
    op.drop_table("findings")
    op.drop_table("asset_relationships")
    op.drop_table("asset_observations")
    op.drop_table("scans")
    op.drop_table("scan_scopes")
    op.drop_table("refresh_tokens")
    op.drop_table("organization_members")
    op.drop_table("oauth_accounts")
    op.drop_index(
        "uq_feature_flags_key_global",
        table_name="feature_flags",
        postgresql_where="organization_id IS NULL",
    )
    op.drop_table("feature_flags")
    op.drop_table("audit_logs")
    op.drop_table("assets")
    op.drop_table("users")
    op.drop_table("system_settings")
    op.drop_table("organizations")
    # ### end Alembic commands ###
